name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      neo4j:
        image: "neo4j:4.4.8-community"
        ports:
          - "7474:7474" # HTTP
          - "7676:7676" # HTTPS
          - "7687:7687" # Bolt
        env:
          NEO4J_AUTH: "none"
          NEO4JLABS_PLUGINS: '["apoc"]'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Cache Maven dependencies
        run: mvn -B package --file pom.xml
      - name: Run Tests
        run: mvn test -ntp -Dnoprint=1
